src/iMovei/agenda/urls.py
from django.urls import path
from iMovei.agenda.views import home, create_visita, read_all, update_visita, detalhar_visita


app_name = 'agenda'

urlpatterns = [
    path('', home, name='home_agenda'),
    path('lista/', read_all, name="lista_visitas"),
    path('cadastro_visita/', create_visita, name="cadastro_visita"),
    path('atualizar/<int:id>/', update_visita, name="atualizar_visita"),
    path('detalhamento/<int:id>/', detalhar_visita, name="detalhamento_visita"),
    #path('excluir/<int:id>/', delete, name="excluir_clientes"),
]

src/iMovei/clientes/urls.py
from django.urls import path
from iMovei.clientes.views import home, read_all, create, update, delete


app_name = 'clientes'

urlpatterns = [
    path('', home, name='home_clientes'),
    path('lista/', read_all, name="lista_clientes"),
    path('cadastro/', create, name="cadastro_clientes"),
    path('atualizar/<int:id>/', update, name="atualizar_clientes"),
    path('excluir/<int:id>/', delete, name="excluir_clientes"),
]

src/iMovei/imoveis/urls.py
from django.urls import path
from iMovei.imoveis.views import home, read_all, create, update, delete


app_name = 'imoveis'

urlpatterns = [
    path('', home, name='home_imoveis'),
    path('lista/', read_all, name="lista_imoveis"),
    path('cadastro/', create, name="cadastro_imoveis"),
    path('atualizar/<int:id>/', update, name="atualizar_imoveis"),
    path('excluir/<int:id>/', delete, name="excluir_imoveis"),
]

src/iMovei/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from iMovei.core import views
from iMovei.imoveis import urls as imoveis_urls
from iMovei.clientes import urls as clientes_urls
from iMovei.agenda import urls as agenda_urls


urlpatterns = [
    path('', views.home, name='home'),
    path('secret/', views.secret_page, name='secret'),
    path('secret2/', views.SecretPage.as_view(), name='secret2'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('clientes/', include(clientes_urls, namespace='clientes')),
    path('imoveis/', include(imoveis_urls, namespace='imoveis')),
    path('agenda/', include(agenda_urls, namespace='agenda'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/iMovei/agenda/models.py
from django.db import models

from iMovei.clientes.models import Cliente
from iMovei.imoveis.models import Imovel


class Visita(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    imovel = models.ForeignKey(Imovel, on_delete=models.CASCADE)
    data_visita = models.DateField(auto_now=False, auto_now_add=False)
    hora_visita = models.TimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return 'Visita {0}: agendada para o dia {1}.'.format(self.id, self.data_visita)

src/iMovei/clientes/models.py
from django.db import models


class Cliente(models.Model):
  pessoa = models.CharField(
    max_length=1,
    choices=(
      ('F', 'Física'),
      ('J', 'Jurídica'),
    ),
    default='F'
  )
  nome = models.CharField(max_length=50, blank=False, default='')
  cpf = models.CharField(max_length=14, blank=False, default='')
  idade = models.PositiveIntegerField()
  sexo = models.CharField(
    max_length=1,
    choices=(
      ('M', 'Masculino'),
      ('F', 'Feminino'),
      ('X', 'Não informado'),
    ),
    default='X'
  )
  email = models.CharField(max_length=50, blank=True)
  telefone = models.CharField(max_length=25, blank=True)
  telefone2 = models.CharField(max_length=25, blank=True)

  def __str__(self):
    return self.nome

src/iMovei/core/models.py
from django.db import models

# Create your models here.

src/iMovei/imoveis/models.py
from django.db import models


class Imovel(models.Model):
  operacao = models.CharField(
    max_length=1,
    choices=(
      ('V', 'Venda'),
      ('L', 'Locação'),
    ),
    default='V'
  )
  finalidade = models.CharField(
    max_length=1,
    choices=(
      ('R', 'Residencial'),
      ('C', 'Comercial'),
    ),
    default='R'
  )
  valor_condominio = models.DecimalField(max_digits=9, decimal_places=2)
  valor_iptu = models.DecimalField(max_digits=9, decimal_places=2)
  garagem = models.PositiveIntegerField()
  tipo_garagem = models.CharField(
    max_length=1,
    choices=(
      ('C', 'Coberta'),
      ('D', 'Descoberta'),
      ('P', 'Parcial'),
    ),
    default='C'
  )
  dormitorios = models.PositiveIntegerField()
  sendo_suite = models.PositiveIntegerField()
  banheiros = models.PositiveIntegerField()
  face = models.CharField(
    max_length=3,
    choices=(
      ('SOM', 'Sombra'),
      ('SOL', 'Sol'),
    ),
    default='SOM'
  )
  area_terreno = models.DecimalField(max_digits=9, decimal_places=2)
  area_construida = models.DecimalField(max_digits=9, decimal_places=2)
  frente = models.DecimalField(max_digits=9, decimal_places=2)
  fundo = models.DecimalField(max_digits=9, decimal_places=2)
  esquerda = models.DecimalField(max_digits=9, decimal_places=2)
  direita = models.DecimalField(max_digits=9, decimal_places=2)

  # ENDEREÇO
  cep = models.CharField(max_length=10, blank=False, default='')
  rua = models.CharField(max_length=50, blank=False, default='')
  numero = models.PositiveIntegerField(blank=False, default=0)
  bairro = models.CharField(max_length=50, blank=False, default='')
  cidade = models.CharField(max_length=30, blank=False, default='')
  estado = models.CharField(max_length=20, blank=False, default='')
  complemento = models.TextField(max_length=150, blank=True)

  def __str__(self):
    return 'Código do imóvel: {}'.format(str(self.id))

src/iMovei/agenda/forms.py
from django.forms import ModelForm
from iMovei.agenda.models import Visita


class VisitaForm(ModelForm):
    class Meta:
        model = Visita
        fields = [
            'cliente',
            'imovel',
            'data_visita',
            'hora_visita'
        ]

src/iMovei/clientes/forms.py
from django.forms import ModelForm
from iMovei.clientes.models import Cliente


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'pessoa',
            'nome',
            'cpf',
            'idade',
            'sexo',
            'email',
            'telefone',
            'telefone2'
        ]

src/iMovei/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

src/iMovei/imoveis/forms.py
from django import forms
from .models import Imovel


class ImovelForm(forms.ModelForm):
    class Meta:
        model = Imovel
        fields = [
            'operacao',
            'finalidade',
            'valor_condominio',
            'valor_iptu',
            'garagem',
            'tipo_garagem',
            'dormitorios',
            'sendo_suite',
            'banheiros',
            'face',
            'area_terreno',
            'area_construida',
            'frente',
            'fundo',
            'esquerda',
            'direita',
            'cep',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado',
            'complemento'
        ]

        widgets = { 
            "cep":forms.TextInput(attrs={
                'name':'cep',
                'type':'text',
                'placeholder':'XXXXX-XXX',
                'id':'cep',
                'onblur':'pesquisacep(this.value);'}),
            "rua":forms.TextInput(attrs={
                'name':'rua',
                'type':'text',
                'id':'rua'}),
            "bairro":forms.TextInput(attrs={
                'name':'bairro',
                'type':'text',
                'id':'bairro'}),
            "cidade":forms.TextInput(attrs={
                'name':'cidade',
                'type':'text',
                'id':'cidade'}),
            "estado":forms.TextInput(attrs={
                'name':'estado',
                'type':'text',
                'id':'uf'}),
        }  

src/iMovei/agenda/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from iMovei.agenda.models import Visita
from iMovei.agenda.forms import VisitaForm


@login_required
def home(request):
    return render(request, 'agenda/home.html')


@login_required
def read_all(request):
    visitas = Visita.objects.all()

    return render(request, 'agenda/lista_visitas.html', {'visitas': visitas})


@login_required
def create_visita(request):
    form = VisitaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('agenda:lista_visitas')
    return render(request, 'agenda/cadastro_visita.html', {'form': form})


@login_required
def update_visita(request, id):
    visita = get_object_or_404(Visita, pk=id)
    form = VisitaForm(request.POST or None, instance=visita)
    if form.is_valid():
        form.save()
        return redirect('agenda:lista_visitas')
    return render(request, 'agenda/cadastro_visita.html', {'form': form})


@login_required
def detalhar_visita(request, id):
    visita = get_object_or_404(Visita, pk=id)

    return render(request, 'agenda/detalhamento_visita.html', {'visita': visita})

src/iMovei/clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from iMovei.clientes.models import Cliente
from iMovei.clientes.forms import ClienteForm


@login_required
def home(request):
    return render(request, 'clientes/home.html')


@login_required
def read_all(request):
    clientes = Cliente.objects.all()
    termo_de_busca = ''

    if 'busca' in request.GET:
        termo_de_busca = request.GET['busca']
        clientes = clientes.filter(nome__icontains=termo_de_busca)

    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes, 'termo_de_busca': termo_de_busca})


@login_required
def create(request):
    form = ClienteForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('clientes:lista_clientes')
    return render(request, 'clientes/cadastro.html', {'form': form})


@login_required
def update(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid():
        form.save()
        return redirect('clientes:lista_clientes')
    return render(request, 'clientes/cadastro.html', {'form': form})


@login_required
def delete(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes:lista_clientes')
    return render(request, 'clientes/confirma_exclusao.html', {'form': form, 'cliente': cliente})

src/iMovei/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from iMovei.core.forms import UserCreationForm


def home(request):
    count = User.objects.count()
    return render(request, 'home.html', {
        'count': count
    })


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })


@login_required
def secret_page(request):
    return render(request, 'secret_page.html')


class SecretPage(LoginRequiredMixin, TemplateView):
    template_name = 'secret_page.html'

src/iMovei/imoveis/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from iMovei.imoveis.models import Imovel
from iMovei.imoveis.forms import ImovelForm


@login_required
def home(request):
    return render(request, 'imoveis/home.html')

@login_required
def read_all(request):
    imoveis = Imovel.objects.all()
    termo_de_busca = ''

    if 'busca' in request.GET:
        termo_de_busca = request.GET['busca']
        imoveis = imoveis.filter(id__icontains=termo_de_busca)
    
    return render(request, 'imoveis/lista_imoveis.html', {'imoveis': imoveis, 'termo_de_busca': termo_de_busca})

@login_required
def create(request):
    form = ImovelForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('imoveis:lista_imoveis')
    return render(request, 'imoveis/cadastro.html', {'form': form})

@login_required
def update(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    form = ImovelForm(request.POST or None, instance=imovel)
    if form.is_valid():
        form.save()
        return redirect('imoveis:lista_imoveis')
    return render(request, 'imoveis/cadastro.html', {'form': form})

@login_required
def delete(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    form = ImovelForm(request.POST or None, instance=imovel)
    if request.method == 'POST':
        imovel.delete()
        return redirect('imoveis:lista_imoveis')
    return render(request, 'imoveis/confirma_exclusao.html', {'form': form, 'imovel': imovel})

src/iMovei/templates/imoveis/cadastro.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<h1 class="mt-2">Cadastro de imóvel</h1>
<hr class="mt-0">
<div class="row justify-content-center">
<div class="col-10">

<div class="card my-4">
<div class="card-body">
    <form action="" method="POST" novalidate>
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
        {{ form.operacao|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.finalidade|as_crispy_field }}
        </div>
    </div>

    <hr>
    <h5 class="mb-0">Valores</h5>
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
        {{ form.valor_condominio|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.valor_iptu|as_crispy_field }}
        </div>
    </div>

    <hr>
    <h5 class="mb-0">Garagem</h5>
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
        {{ form.garagem|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.tipo_garagem|as_crispy_field }}
        </div>
    </div>

    <hr>
    <h5 class="mb-0">Cômodos</h5>
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
        {{ form.dormitorios|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.sendo_suite|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.banheiros|as_crispy_field }}
        </div>
    </div>

    <hr>
    <h5 class="mb-0">Construção</h5>
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
        {{ form.face|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.area_terreno|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.area_construida|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
        {{ form.frente|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.fundo|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.esquerda|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
        {{ form.direita|as_crispy_field }}
        </div>
    </div>

    <hr>
    <h5 class="mb-0">Endereço</h5>
    <div class="form-row">
        <div class="form-group col-md-3 mb-0">
            {{ form.cep|as_crispy_field }}
        </div>
        <div class="form-group col-md-3 mb-0">
            {{ form.estado|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12 mb-0">
            {{ form.rua|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2 mb-0">
            {{ form.numero|as_crispy_field }}
        </div>
        <div class="form-group col-md-5 mb-0">
            {{ form.bairro|as_crispy_field }}
        </div>
        <div class="form-group col-md-5 mb-0">
            {{ form.cidade|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-12 mb-0">
            {{ form.complemento|as_crispy_field }}
        </div>
    </div>

    <button class="btn btn-success" type="submit">Salvar</button>
    <a class="btn btn-primary" href="{% url 'imoveis:lista_imoveis' %}">Lista</a>
    </form>
</div>
</div>

</div>
</div>
</div>
{% endblock content %}

src/iMovei/templates/imoveis/confirma_exclusao.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container">
    <h2 class="mb-2">Atenção! Deseja excluir o imóvel {{ imovel.id }} ?</h2>

    <form action="" method="POST">
        {% csrf_token %}
        <button class="btn btn-success" type="submit">Confirmar</button>
        <a class="btn btn-danger" href="{% url 'imoveis:lista_imoveis' %}">Cancelar</a>
    </form>
</div>
{% endblock content %}

src/iMovei/templates/imoveis/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Página inicial da app Imóveis!</h1>
{% endblock content %}

src/iMovei/templates/imoveis/lista_imoveis.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<h1>Imóveis</h1>
<hr>
<div class="row justify-content-center">
    <div class="col-10">

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Digite aqui sua busca" aria-label="Busca"
                name="busca">
            <button class="btn btn-outline-success my-2 my-sm-0 mr-sm-2" type="submit">Ir</button>
            <a class="btn btn-primary" href="{% url 'imoveis:lista_imoveis' %}">Limpar busca</a>
        </form>

        <div class="card my-2">
            <div class="card-body">
                {% for imovel in imoveis %}
                <div class="card my-2">
                    <div class="card-body">
                        <h5>{{ imovel }}</h5>
                        <a class="btn btn-outline-primary btn-sm" href="{% url 'imoveis:atualizar_imoveis' imovel.id %}">Detalhar / Editar</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'imoveis:excluir_imoveis' imovel.id %}">Excluir</a>
                    </div>
                </div>
                {% endfor %}
                <a class="btn btn-primary" href="{% url 'imoveis:cadastro_imoveis' %}">Cadastro</a>
            </div>
        </div>

    </div>
</div>
</div>
{% endblock content %}