src/iMovei/agenda/urls.py
from django.urls import path
from iMovei.agenda.views import home, create_visita, read_all, update_visita, detalhar_visita


app_name = 'agenda'

urlpatterns = [
    path('', home, name='home_agenda'),
    path('lista/', read_all, name="lista_visitas"),
    path('cadastro_visita/', create_visita, name="cadastro_visita"),
    path('atualizar/<int:id>/', update_visita, name="atualizar_visita"),
    path('detalhamento/<int:id>/', detalhar_visita, name="detalhamento_visita"),
    #path('excluir/<int:id>/', delete, name="excluir_clientes"),
]

src/iMovei/clientes/urls.py
from django.urls import path
from iMovei.clientes.views import home, read_all, create, update, delete


app_name = 'clientes'

urlpatterns = [
    path('', home, name='home_clientes'),
    path('lista/', read_all, name="lista_clientes"),
    path('cadastro/', create, name="cadastro_clientes"),
    path('atualizar/<int:id>/', update, name="atualizar_clientes"),
    path('excluir/<int:id>/', delete, name="excluir_clientes"),
]

src/iMovei/imoveis/urls.py
from django.urls import path
from iMovei.imoveis.views import home, read_all, create, update, delete


app_name = 'imoveis'

urlpatterns = [
    path('', home, name='home_imoveis'),
    path('lista/', read_all, name="lista_imoveis"),
    path('cadastro/', create, name="cadastro_imoveis"),
    path('atualizar/<int:id>/', update, name="atualizar_imoveis"),
    path('excluir/<int:id>/', delete, name="excluir_imoveis"),
]

src/iMovei/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from iMovei.core import views
from iMovei.imoveis import urls as imoveis_urls
from iMovei.clientes import urls as clientes_urls
from iMovei.agenda import urls as agenda_urls


urlpatterns = [
    path('', views.home, name='home'),
    path('secret/', views.secret_page, name='secret'),
    path('secret2/', views.SecretPage.as_view(), name='secret2'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('clientes/', include(clientes_urls, namespace='clientes')),
    path('imoveis/', include(imoveis_urls, namespace='imoveis')),
    path('agenda/', include(agenda_urls, namespace='agenda'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/iMovei/agenda/models.py
from django.db import models

from iMovei.clientes.models import Cliente
from iMovei.imoveis.models import Imovel


class Visita(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    imovel = models.ForeignKey(Imovel, on_delete=models.CASCADE)
    data_visita = models.DateField(auto_now=False, auto_now_add=False)
    hora_visita = models.TimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return 'Visita {0}: agendada para o dia {1}.'.format(self.id, self.data_visita)

src/iMovei/clientes/models.py
from django.db import models


class Cliente(models.Model):
  pessoa = models.CharField(
    max_length=1,
    choices=(
      ('F', 'Física'),
      ('J', 'Jurídica'),
    ),
    default='F'
  )
  nome = models.CharField(max_length=50, blank=False, default='')
  cpf = models.CharField(max_length=14, blank=False, default='')
  idade = models.PositiveIntegerField()
  sexo = models.CharField(
    max_length=1,
    choices=(
      ('M', 'Masculino'),
      ('F', 'Feminino'),
      ('X', 'Não informado'),
    ),
    default='X'
  )
  email = models.CharField(max_length=50, blank=True)
  telefone = models.CharField(max_length=25, blank=True)
  telefone2 = models.CharField(max_length=25, blank=True)

  def __str__(self):
    return self.nome

src/iMovei/core/models.py
from django.db import models

# Create your models here.

src/iMovei/imoveis/models.py
from django.db import models


class Imovel(models.Model):
  operacao = models.CharField(
    max_length=1,
    choices=(
      ('V', 'Venda'),
      ('L', 'Locação'),
    ),
    default='V'
  )
  finalidade = models.CharField(
    max_length=1,
    choices=(
      ('R', 'Residencial'),
      ('C', 'Comercial'),
    ),
    default='R'
  )
  valor_condominio = models.DecimalField(max_digits=9, decimal_places=2)
  valor_iptu = models.DecimalField(max_digits=9, decimal_places=2)
  garagem = models.PositiveIntegerField()
  tipo_garagem = models.CharField(
    max_length=1,
    choices=(
      ('C', 'Coberta'),
      ('D', 'Descoberta'),
      ('P', 'Parcial'),
    ),
    default='C'
  )
  dormitorios = models.PositiveIntegerField()
  sendo_suite = models.PositiveIntegerField()
  banheiros = models.PositiveIntegerField()
  face = models.CharField(
    max_length=3,
    choices=(
      ('SOM', 'Sombra'),
      ('SOL', 'Sol'),
    ),
    default='SOM'
  )
  area_terreno = models.DecimalField(max_digits=9, decimal_places=2)
  area_construida = models.DecimalField(max_digits=9, decimal_places=2)
  frente = models.DecimalField(max_digits=9, decimal_places=2)
  fundo = models.DecimalField(max_digits=9, decimal_places=2)
  esquerda = models.DecimalField(max_digits=9, decimal_places=2)
  direita = models.DecimalField(max_digits=9, decimal_places=2)

  # ENDEREÇO
  cep = models.CharField(max_length=10, blank=False, default='')
  rua = models.CharField(max_length=50, blank=False, default='')
  numero = models.PositiveIntegerField(blank=False, default=0)
  bairro = models.CharField(max_length=50, blank=False, default='')
  cidade = models.CharField(max_length=30, blank=False, default='')
  estado = models.CharField(max_length=20, blank=False, default='')
  complemento = models.TextField(max_length=150, blank=True)

  def __str__(self):
    return 'Código do imóvel: {}'.format(str(self.id))

src/iMovei/agenda/forms.py
from django.forms import ModelForm
from iMovei.agenda.models import Visita


class VisitaForm(ModelForm):
    class Meta:
        model = Visita
        fields = [
            'cliente',
            'imovel',
            'data_visita',
            'hora_visita'
        ]

src/iMovei/clientes/forms.py
from django.forms import ModelForm
from iMovei.clientes.models import Cliente


class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'pessoa',
            'nome',
            'cpf',
            'idade',
            'sexo',
            'email',
            'telefone',
            'telefone2'
        ]

src/iMovei/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

src/iMovei/imoveis/forms.py
from django import forms
from .models import Imovel


class ImovelForm(forms.ModelForm):
    class Meta:
        model = Imovel
        fields = [
            'operacao',
            'finalidade',
            'valor_condominio',
            'valor_iptu',
            'garagem',
            'tipo_garagem',
            'dormitorios',
            'sendo_suite',
            'banheiros',
            'face',
            'area_terreno',
            'area_construida',
            'frente',
            'fundo',
            'esquerda',
            'direita',
            'cep',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado',
            'complemento'
        ]

        widgets = { 
            "cep":forms.TextInput(attrs={
                'name':'cep',
                'type':'text',
                'placeholder':'XXXXX-XXX',
                'id':'cep',
                'onblur':'pesquisacep(this.value);'}),
            "rua":forms.TextInput(attrs={
                'name':'rua',
                'type':'text',
                'id':'rua'}),
            "bairro":forms.TextInput(attrs={
                'name':'bairro',
                'type':'text',
                'id':'bairro'}),
            "cidade":forms.TextInput(attrs={
                'name':'cidade',
                'type':'text',
                'id':'cidade'}),
            "estado":forms.TextInput(attrs={
                'name':'estado',
                'type':'text',
                'id':'uf'}),
        }  

src/iMovei/agenda/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from iMovei.agenda.models import Visita
from iMovei.agenda.forms import VisitaForm


@login_required
def home(request):
    return render(request, 'agenda/home.html')


@login_required
def read_all(request):
    visitas = Visita.objects.all()

    return render(request, 'agenda/lista_visitas.html', {'visitas': visitas})


@login_required
def create_visita(request):
    form = VisitaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('agenda:lista_visitas')
    return render(request, 'agenda/cadastro_visita.html', {'form': form})


@login_required
def update_visita(request, id):
    visita = get_object_or_404(Visita, pk=id)
    form = VisitaForm(request.POST or None, instance=visita)
    if form.is_valid():
        form.save()
        return redirect('agenda:lista_visitas')
    return render(request, 'agenda/cadastro_visita.html', {'form': form})


@login_required
def detalhar_visita(request, id):
    visita = get_object_or_404(Visita, pk=id)

    return render(request, 'agenda/detalhamento_visita.html', {'visita': visita})

src/iMovei/clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from iMovei.clientes.models import Cliente
from iMovei.clientes.forms import ClienteForm


@login_required
def home(request):
    return render(request, 'clientes/home.html')


@login_required
def read_all(request):
    clientes = Cliente.objects.all()
    termo_de_busca = ''

    if 'busca' in request.GET:
        termo_de_busca = request.GET['busca']
        clientes = clientes.filter(nome__icontains=termo_de_busca)

    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes, 'termo_de_busca': termo_de_busca})


@login_required
def create(request):
    form = ClienteForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('clientes:lista_clientes')
    return render(request, 'clientes/cadastro.html', {'form': form})


@login_required
def update(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid():
        form.save()
        return redirect('clientes:lista_clientes')
    return render(request, 'clientes/cadastro.html', {'form': form})


@login_required
def delete(request, id):
    cliente = get_object_or_404(Cliente, pk=id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes:lista_clientes')
    return render(request, 'clientes/confirma_exclusao.html', {'form': form, 'cliente': cliente})

src/iMovei/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from iMovei.core.forms import UserCreationForm


def home(request):
    count = User.objects.count()
    return render(request, 'home.html', {
        'count': count
    })


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })


@login_required
def secret_page(request):
    return render(request, 'secret_page.html')


class SecretPage(LoginRequiredMixin, TemplateView):
    template_name = 'secret_page.html'

src/iMovei/imoveis/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from iMovei.imoveis.models import Imovel
from iMovei.imoveis.forms import ImovelForm


@login_required
def home(request):
    return render(request, 'imoveis/home.html')

@login_required
def read_all(request):
    imoveis = Imovel.objects.all()
    termo_de_busca = ''

    if 'busca' in request.GET:
        termo_de_busca = request.GET['busca']
        imoveis = imoveis.filter(id__icontains=termo_de_busca)
    
    return render(request, 'imoveis/lista_imoveis.html', {'imoveis': imoveis, 'termo_de_busca': termo_de_busca})

@login_required
def create(request):
    form = ImovelForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('imoveis:lista_imoveis')
    return render(request, 'imoveis/cadastro.html', {'form': form})

@login_required
def update(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    form = ImovelForm(request.POST or None, instance=imovel)
    if form.is_valid():
        form.save()
        return redirect('imoveis:lista_imoveis')
    return render(request, 'imoveis/cadastro.html', {'form': form})

@login_required
def delete(request, id):
    imovel = get_object_or_404(Imovel, pk=id)
    form = ImovelForm(request.POST or None, instance=imovel)
    if request.method == 'POST':
        imovel.delete()
        return redirect('imoveis:lista_imoveis')
    return render(request, 'imoveis/confirma_exclusao.html', {'form': form, 'imovel': imovel})

src/iMovei/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}iMovei{% endblock title %}</title>
    <style type="text/css">
    .asteriskField {
        display: none;
    }

    form .alert ul li {
        list-style: none;
    }

    form .alert ul {
        padding: 0;
        margin: 0;
    }
    </style>

    <!-- Adicionando Javascript -->
    <script type="text/javascript" >
    
        function limpa_formulário_cep() {
            //Limpa valores do formulário de cep.
            document.getElementById('rua').value=("");
            document.getElementById('bairro').value=("");
            document.getElementById('cidade').value=("");
            document.getElementById('uf').value=("");
            //document.getElementById('ibge').value=("");
        }
    
        function meu_callback(conteudo) {
            if (!("erro" in conteudo)) {
                //Atualiza os campos com os valores.
                document.getElementById('rua').value=(conteudo.logradouro);
                document.getElementById('bairro').value=(conteudo.bairro);
                document.getElementById('cidade').value=(conteudo.localidade);
                document.getElementById('uf').value=(conteudo.uf);
                //document.getElementById('ibge').value=(conteudo.ibge);
            } //end if.
            else {
                //CEP não Encontrado.
                limpa_formulário_cep();
                alert("CEP não encontrado.");
            }
        }
            
        function pesquisacep(valor) {
    
            //Nova variável "cep" somente com dígitos.
            var cep = valor.replace(/\D/g, '');
    
            //Verifica se campo cep possui valor informado.
            if (cep != "") {
    
                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;
    
                //Valida o formato do CEP.
                if(validacep.test(cep)) {
    
                    //Preenche os campos com "..." enquanto consulta webservice.
                    document.getElementById('rua').value="...";
                    document.getElementById('bairro').value="...";
                    document.getElementById('cidade').value="...";
                    document.getElementById('uf').value="...";
                    //document.getElementById('ibge').value="...";
    
                    //Cria um elemento javascript.
                    var script = document.createElement('script');
    
                    //Sincroniza com o callback.
                    script.src = 'https://viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';
    
                    //Insere script no documento e carrega o conteúdo.
                    document.body.appendChild(script);
    
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        };
    
    </script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">iMovei</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Clientes</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!--<a class="dropdown-item" href="{% url 'clientes:home_clientes' %}">Home</a>-->
                        <a class="dropdown-item" href="{% url 'clientes:cadastro_clientes' %}">Cadastro</a>
                        <a class="dropdown-item" href="{% url 'clientes:lista_clientes' %}">Listagem</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Imóveis</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!--<a class="dropdown-item" href="{% url 'imoveis:home_imoveis' %}">Home</a>-->
                        <a class="dropdown-item" href="{% url 'imoveis:cadastro_imoveis' %}">Cadastro</a>
                        <a class="dropdown-item" href="{% url 'imoveis:lista_imoveis' %}">Listagem</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Agenda</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!--<a class="dropdown-item" href="{% url 'agenda:home_agenda' %}">Home</a>-->
                        <a class="dropdown-item" href="{% url 'agenda:cadastro_visita' %}">Cadastro</a>
                        <a class="dropdown-item" href="{% url 'agenda:lista_visitas' %}">Listagem</a>
                    </div>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secret2' %}">Secret page (class-based view)</a>
                </li>
                -->
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'password_change' %}">Alterar senha</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline my-2 my-lg-0">
                <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Cadastre-se</a>
            </form>
            {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

src/iMovei/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div id="carouselSite" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#carouselSite" data-slide-to="0" class="active"></li>
        <li data-target="#carouselSite" data-slide-to="1"></li>
        <li data-target="#carouselSite" data-slide-to="2"></li>
        {% if user.is_authenticated %}
        {% else %}
        <li data-target="#carouselSite" data-slide-to="3"></li>
        {% endif %}
    </ol>

    <div class="carousel-inner">

        <div class="carousel-item active">
            <img src="{% static 'home/slide1.jpg' %}" class="img-fluid d-block">

            <div class="carousel-caption d-none d-sm-block">

                <h3 style="color: #343A40">Gerencie suas opotunidades!</h3>
                <p style="color: #343A40">Cadastre imóveis de forma fácil</p> 

            </div>
        </div>

        <div class="carousel-item">
            <img src="{% static 'home/slide2.jpg' %}" class="img-fluid d-block">

            <div class="carousel-caption d-none d-sm-block">

                <h3 style="color: #343A40">Não perca clientes!</h3>
                <p style="color: #343A40">Cadastre-os e não deixe passar uma venda</p> 

            </div>
        </div>

        <div class="carousel-item">
            <img src="{% static 'home/slide3.jpg' %}" class="img-fluid d-block">

            <div class="carousel-caption d-none d-sm-block">

                <h3 style="color: #343A40">Organize seu trabalho!</h3>
                <p style="color: #343A40">Agende visitas e crie lembretes</p>

            </div>
        </div>

        {% if user.is_authenticated %}
        {% else %}
        <div class="carousel-item">
            <img src="{% static 'home/slide4.jpg' %}" class="img-fluid d-block">

            <div class="carousel-caption d-none d-sm-block">

                <h2>Não possui uma conta?</h2>
                <a href="{% url 'signup' %}" class="btn btn-lg btn-primary">Cadastre-se</a>
                <br>
                <h2>ou</h2>
                <a href="{% url 'login' %}" class="btn btn-lg btn-success">Login</a>

            </div>
        </div>
        {% endif %}

    </div>

    <a href="#carouselSite" class="carousel-control-prev" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
        <span class="sr-only">Anterior</span>
    </a>

    <a href="#carouselSite" class="carousel-control-next" role="button" data-slide="next">
        <span class="carousel-control-next-icon"></span>
        <span class="sr-only">Próximo</span>
    </a>

</div>
{% endblock content %}

src/iMovei/templates/secret_page.html
{% extends 'base.html' %}

{% block content %}
    <p>This is a secret page!</p>
{% endblock content %}